blank_issues_enabled: true
contact_links:
  - name: Advent of CodSpeed Homepage
    url: 'https://codspeed.io/advent'
    about: Learn more about Advent of CodSpeed and how to participate
  - name: Support and questions
    url: 'https://discord.gg/p4jTaunHwA'
    about: Get help and discuss about Advent of CodSpeed on the CodSpeed Discord server
